version: 2

jobs:
  deploy:
    working_directory: /tmp/ruby-getting-started
    docker:
      - image: rvillage/heroku-cli:6.16-alpine
    steps:
      - checkout
      - run: apk --update add --no-cache git openssh
      - run:
          name: Deploy Heroku
          command: git push https://heroku:${HEROKU_API_KEY}@git.heroku.com/${HEROKU_APP_NAME}.git master

workflows:
  version: 2

  build-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
