default: &default
  adapter:  postgresql
  encoding: utf-8
  host:     127.0.0.1
  username: postgres
  password:
  pool:     5

development:
  <<: *default
  database: ruby-getting-started_development

test:
  <<: *default
  database: ruby-getting-started_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
